name: Maven and Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install missing dependencies locally
        run: |
          mvn install:install-file -Dfile=libs/cose-1.6.jar -DgroupId=com.authlete -DartifactId=cose -Dversion=1.6 -Dpackaging=jar
          mvn install:install-file -Dfile=libs/cwt-1.6.jar -DgroupId=com.authlete -DartifactId=cwt -Dversion=1.6 -Dpackaging=jar


      - name: Build with Maven
        working-directory: ./CWTSign
        run: |
          mvn clean package -DskipTests
          cp target/*.jar ../

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t abhishek8shankar/cwtsign:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push abhishek8shankar/cwtsign:latest
