name: Maven and Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        working-directory: ./CWTSign
        run: |
          mvn clean package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: cwtsign-jar
          path: ./CWTSign/target/*.jar

  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: build  # Ensure this runs after the Maven build job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: cwtsign-jar
          path: ./build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.ACTOR_DOCKER_HUB }}
          password: ${{ secrets.RELEASE_DOCKER_HUB}}

      - name: Prepare JAR for Docker
        run: cp ./build/*.jar ./app.jar

      - name: Build Docker image
        run: |
             cd ${{ inputs.SERVICE_LOCATION }}
             docker build -t ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}/${{ secrets.RELEASE_DOCKER_HUB }}:latest .


      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}/${{ secrets.RELEASE_DOCKER_HUB }}:latest
